#!/usr/bin/env bash
#
# Pre Commit hook to run checks against the staged files
# The way this works is for every type of file (or files)
# that need to be checked, we use `git diff --cached` along
# with a filter to determine if any are staged. If so,
#  run the appropriate check.

set -eou pipefail

[[ "${DEBUG:-}" ]] && set -x

echo "Running pre-commit checks"

commands=(ls-lint pnpm)
commandsNotFound=()
for cmd in "${commands[@]}"; do
  if ! command -v "$cmd" &>/dev/null; then
    commandsNotFound+=("$cmd")
  fi
done

if [[ ${#commandsNotFound[@]} -ne 0 ]]; then
  echo -e "\e[41;30mERROR\e[0m" >&2
  echo "The following required commands are not installed: ${commandsNotFound[*]}" >&2
  echo "Please install them to proceed." >&2
  exit 1
fi

# Add cspell things for this file here that we don't need elsewhere.
# cSpell:words ACMRT,ACRT

## Git Diff Filter Cheat Sheet:
# A: Added files - new files that have been staged for commit
# C: Copied files - files that have been copied and staged for commit
# D: Deleted files - files that have been deleted and staged for commit
# M: Modified files - files that have been modified and staged for commit
# R: Renamed files - files that have been renamed and staged for commit
# T: Type changed files - files whose file type has been changed and staged for commit
# ---
# U: Unmerged files - files that have merge conflicts and are staged for commit
# X: Unknown files - files that are staged for commit but Git cannot determine their status
# B: Broken pairing files - files that have been staged for commit but Git cannot determine their status due to a broken pairing (e.g., a file that was renamed but the original file is missing)

## LS Lint applicable files mods are: added, copied, renamed, type changed
if [[ ! -z "$(git diff --cached --name-only --diff-filter=ACRT)" ]]; then
  echo "Running ls-lint"
  ls-lint "${DEBUG:+--debug}"
fi

## Markdownlint applicable files are: added, type changed, modified
staged_markdown_files=$(git diff --cached --name-only --diff-filter=AMT -- '*.md' '.markdownlint-cli2.mjs')
if [[ ! -z "$staged_markdown_files" ]]; then
  echo "Running markdownlint"
  # remove .markdownlint-cli2.mjs from the list of files to check since it is config and not linted here
  staged_markdown_files=$(echo "$staged_markdown_files" | grep -v '.markdownlint-cli2.mjs')
  # convert newlines to spaces for the markdownlint command
  staged_markdown_files=$(echo "$staged_markdown_files" | tr '\n' ' ')
  IFS=' ' read -r -a staged_markdown_files_array <<<"$staged_markdown_files"
  pnpm dlx markdownlint-cli2 "${staged_markdown_files_array[@]}"
fi

## Scan all bin folders even in subdirectories
staged_bin_files=$(git diff --cached --name-only --diff-filter=ACMRT -- '.githooks/*' '*.sh')
# exclude markdown files from being made executable
staged_bin_files=$(echo "$staged_bin_files" | grep -v '\.md$')
if [[ ! -z "$staged_bin_files" ]]; then
  echo "Working on shell scripts"
  while IFS= read -r file; do
    if [[ -f "$file" ]]; then
      chmod +x "$file"
      shfmt -w "$file"
      git add "$file"
    fi
  done <<<"$staged_bin_files"
fi

## Scan all workflow files in .github/workflows
staged_workflow_files=$(git diff --cached --name-only --diff-filter=ACMRT -- '.github/workflows/*.yml')
if [[ ! -z "$staged_workflow_files" ]]; then
  echo "Running scans for Github Actions workflow files"
  staged_workflow_files=$(echo "$staged_workflow_files" | tr '\n' ' ')
  IFS=' ' read -r -a staged_workflow_files_array <<<"$staged_workflow_files"
  zizmor --persona auditor "${staged_workflow_files_array[@]}"
  actionlint "${staged_workflow_files_array[@]}"
fi

## Get all Dockerfiles that have been added, copied, or modified
staged_dockerfiles=$(git diff --cached --name-only --diff-filter=ACM -- '**/Dockerfile')
if [[ ! -z "$staged_dockerfiles" ]]; then
  echo "Running hadolint"
  staged_dockerfiles=$(echo "$staged_dockerfiles" | tr '\n' ' ')
  IFS=' ' read -r -a staged_dockerfiles_array <<<"$staged_dockerfiles"
  for dockerfile in "${staged_dockerfiles_array[@]}"; do
    echo "---- Linting $dockerfile"
    hadolint "$dockerfile"
  done
fi

echo -e "\e[42;30mSUCCESS\e[0m"
echo "Pre-commit checks passed"
